prod:
  hostname: 51.77.136.30
  user: root
  # branch: "master"
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  deploy_path: /var/www/deployer-demo
  keep_releases: 3